import React, { useState, useRef, useEffect } from 'react';
import { Device, DeviceType, DeviceStatus, SnmpVersion, AVAILABLE_LOCATIONS } from '../types';
import { apiService } from '../services/apiService';
import { 
  Server, Shield, Globe, Lock, Save, Radio, CheckCircle, XCircle, 
  RotateCw, Monitor, Wifi, Settings, FileDown, FileUp, FileSpreadsheet, UploadCloud, Trash2, Brain,
  Key, LockKeyhole
} from './Icons';

interface AdminPanelProps {
  onAddDevice: (device: Device) => Promise<void>;
  onAskAi: (message: string) => void;
}

const AdminPanel: React.FC<AdminPanelProps> = ({ onAddDevice, onAskAi }) => {
  const [loading, setLoading] = useState(false);
  const [testStatus, setTestStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [statusMessage, setStatusMessage] = useState('');
  const [submitStatus, setSubmitStatus] = useState<'idle' | 'success' | 'error'>('idle');
  
  // Security / PIN State
  const [currentPin, setCurrentPin] = useState('');
  const [newPin, setNewPin] = useState('');
  const [pinMessage, setPinMessage] = useState('');

  // Bulk Import State
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importedDevices, setImportedDevices] = useState<Device[]>([]);
  const [importError, setImportError] = useState('');
  const [rawCsvData, setRawCsvData] = useState('');

  const [formData, setFormData] = useState({
    name: '',
    ip: '',
    type: DeviceType.SERVER,
    location: AVAILABLE_LOCATIONS[0] as string,
    // SNMP Config
    snmpVersion: SnmpVersion.V2C,
    snmpPort: 161,
    snmpCommunity: 'public',
    snmpUser: '',
    snmpAuth: 'SHA',
    snmpPriv: 'AES'
  });

  // Load PIN on mount
  useEffect(() => {
    const savedPin = localStorage.getItem('NETSENTINEL_KIOSK_PIN');
    if (savedPin) setCurrentPin(savedPin);
    else setCurrentPin('0000'); // Default
  }, []);

  const handleUpdatePin = (e: React.FormEvent) => {
    e.preventDefault();
    if (newPin.length < 4) {
      setPinMessage('PIN must be at least 4 digits');
      return;
    }
    localStorage.setItem('NETSENTINEL_KIOSK_PIN', newPin);
    setCurrentPin(newPin);
    setNewPin('');
    setPinMessage('Access PIN updated successfully.');
    setTimeout(() => setPinMessage(''), 3000);
  };

  // --- Manual Add Logic ---

  const handleTestConnection = async () => {
    if (!formData.ip) {
      setTestStatus('error');
      setStatusMessage('IP Address is required');
      return;
    }

    setLoading(true);
    setTestStatus('idle');
    setStatusMessage('Testing SNMP connection...');

    try {
      const snmpConfig = {
        version: formData.snmpVersion,
        port: formData.snmpPort,
        community: formData.snmpVersion !== SnmpVersion.V3 ? formData.snmpCommunity : undefined,
        username: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpUser : undefined,
        authProtocol: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpAuth : undefined,
        privProtocol: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpPriv : undefined,
        timeout: 5000,
      };

      const response = await apiService.testSnmpConnection(formData.ip, snmpConfig);
      
      setLoading(false);
      setTestStatus('success');
      setStatusMessage(`✅ ${response.data.message || 'Connection successful'}`);
    } catch (error: any) {
      setLoading(false);
      setTestStatus('error');
      const errorMessage = error.message || `Failed to connect to ${formData.ip} on port ${formData.snmpPort}`;
      setStatusMessage(`❌ ${errorMessage}`);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Auto-test before adding if not tested
    if (testStatus !== 'success') {
      handleTestConnection();
      return; 
    }

    setLoading(true);
    setStatusMessage('Adding device to monitoring system...');

    try {
      // Device data will be set by backend API with default values
      const newDevice: Device = {
        id: '', // Will be generated by backend
        name: formData.name,
        ip: formData.ip,
        type: formData.type,
        status: DeviceStatus.OFFLINE, // Default to OFFLINE until monitored
        location: formData.location,
        cpuUsage: 0, // Default values - backend will update when device is monitored
        memoryUsage: 0,
        temperature: null,
        uptime: 0,
        lastSeen: new Date().toISOString(),
        snmpConfig: {
          version: formData.snmpVersion,
          port: formData.snmpPort,
          community: formData.snmpVersion !== SnmpVersion.V3 ? formData.snmpCommunity : undefined,
          username: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpUser : undefined,
          authProtocol: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpAuth : undefined,
          privProtocol: formData.snmpVersion === SnmpVersion.V3 ? formData.snmpPriv : undefined,
          timeout: 2000
        }
      };

      await onAddDevice(newDevice);
      
      // Reset form on success
      setFormData({
        ...formData,
        name: '',
        ip: '',
        location: AVAILABLE_LOCATIONS[0],
        snmpCommunity: 'public',
        snmpUser: '',
      });
      setTestStatus('idle');
      setSubmitStatus('success');
      setStatusMessage('✅ Device added successfully! It will appear in the device list shortly.');
      setTimeout(() => {
        setStatusMessage('');
        setSubmitStatus('idle');
      }, 5000);
    } catch (error: any) {
      setSubmitStatus('error');
      setStatusMessage(`❌ Error: ${error.message || 'Failed to add device'}`);
    } finally {
      setLoading(false);
    }
  };

  // --- Bulk Import/Export Logic ---

  const handleDownloadTemplate = () => {
    const headers = ['name', 'ip', 'type', 'location', 'snmpVersion', 'snmpPort', 'snmpCommunity'];
    const sample = ['Server-02', '192.168.1.102', 'SERVER', 'Rack 2', 'v2c', '161', 'public'];
    
    const csvContent = "data:text/csv;charset=utf-8," 
      + headers.join(",") + "\n" + sample.join(",");
      
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "device_import_template.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const parseCSV = (text: string) => {
    setRawCsvData(text); // Save for AI analysis
    const lines = text.split('\n');
    const devices: Device[] = [];
    let errorCount = 0;

    // Start from index 1 to skip header
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;
      
      const cols = line.split(',');
      if (cols.length < 2) {
        errorCount++;
        continue;
      }

      const [name, ip, typeStr, location, verStr, portStr, community] = cols.map(c => c.trim());

      // Simple Validation
      if (!name || !ip) {
        errorCount++;
        continue;
      }

      // Map Type
      let type = DeviceType.SERVER;
      const tUpper = typeStr?.toUpperCase();
      if (tUpper === 'NETWORK') type = DeviceType.NETWORK;
      if (tUpper === 'PC') type = DeviceType.PC;
      if (tUpper === 'IOT') type = DeviceType.IOT;

      // Map Version
      let version = SnmpVersion.V2C;
      if (verStr === 'v1') version = SnmpVersion.V1;
      if (verStr === 'v3') version = SnmpVersion.V3;

      devices.push({
        id: `import-${Date.now()}-${i}`,
        name,
        ip,
        type,
        status: DeviceStatus.ONLINE, // Assume online until checked
        location: location || 'Unknown',
        cpuUsage: 0,
        memoryUsage: 0,
        temperature: 0,
        uptime: 0,
        lastSeen: new Date().toISOString(),
        snmpConfig: {
          version,
          port: parseInt(portStr) || 161,
          community: community || 'public',
          timeout: 2000
        }
      });
    }

    if (devices.length === 0 || errorCount > 0) {
      setImportError(`Found ${devices.length} valid devices, but ${errorCount} rows had errors.`);
    } else {
      setImportError('');
    }
    
    setImportedDevices(devices);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      const text = evt.target?.result as string;
      parseCSV(text);
    };
    reader.readAsText(file);
  };

  const confirmImport = async () => {
    // Add devices sequentially to avoid overwhelming the API
    setLoading(true);
    setStatusMessage(`Adding ${importedDevices.length} devices...`);
    try {
      for (const device of importedDevices) {
        await onAddDevice(device);
      }
      setStatusMessage(`✅ Successfully added ${importedDevices.length} devices!`);
      setImportedDevices([]);
      setRawCsvData('');
      setTimeout(() => setStatusMessage(''), 5000);
    } catch (error: any) {
      setStatusMessage(`❌ Error: ${error.message || 'Failed to add some devices'}`);
    } finally {
      setLoading(false);
    }
    if (fileInputRef.current) fileInputRef.current.value = '';
    setImportError('');
  };

  const removeImportItem = (id: string) => {
    setImportedDevices(prev => prev.filter(d => d.id !== id));
  };

  const handleAnalyzeError = () => {
    const headers = rawCsvData.split('\n')[0];
    const prompt = `
I encountered an error while importing network devices from a CSV file.
Error Message: "${importError}"

Expected CSV Header format: name, ip, type, location, snmpVersion, snmpPort, snmpCommunity

Actual CSV Header: "${headers}"

Here is a sample of the raw CSV data causing issues:
\`\`\`csv
${rawCsvData.substring(0, 1500)}
\`\`\`

Please analyze the structure and content. Look for:
1. Header mismatches or missing columns.
2. Invalid IP address formats.
3. Incorrect data types (e.g., text in port number).
4. Formatting issues like missing commas or extra quotes.
5. Provide the corrected CSV format for the first 3 rows if possible.
`;
    onAskAi(prompt);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 animate-fade-in pb-10">
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Manual Add (takes up 2/3 on large screens) */}
        <div className="lg:col-span-2 bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-xl h-fit">
          <div className="flex items-center gap-4 border-b border-slate-700 pb-6 mb-6">
            <div className="p-3 bg-blue-600 rounded-lg shadow-lg">
              <Settings className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Device Onboarding</h2>
              <p className="text-slate-400 text-sm">Add single infrastructure via SNMP</p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Basic Info */}
            <div>
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                <Globe className="w-4 h-4" /> General Information
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-xs font-medium text-slate-400">Device Name</label>
                  <input 
                    required
                    type="text" 
                    placeholder="e.g., CORE-SW-01"
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all text-sm"
                    value={formData.name}
                    onChange={e => setFormData({...formData, name: e.target.value})}
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-slate-400">IP Address</label>
                  <input 
                    required
                    type="text" 
                    placeholder="e.g., 192.168.1.1"
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all font-mono text-sm"
                    value={formData.ip}
                    onChange={e => setFormData({...formData, ip: e.target.value})}
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-slate-400">Location</label>
                  <select 
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all text-sm"
                    value={formData.location}
                    onChange={e => setFormData({...formData, location: e.target.value})}
                  >
                    {AVAILABLE_LOCATIONS.map(loc => (
                      <option key={loc} value={loc}>{loc}</option>
                    ))}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-slate-400">Type</label>
                  <select
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                    value={formData.type}
                    onChange={e => setFormData({...formData, type: e.target.value as DeviceType})}
                  >
                    <option value={DeviceType.SERVER}>Server</option>
                    <option value={DeviceType.NETWORK}>Network</option>
                    <option value={DeviceType.PC}>PC Workstation</option>
                    <option value={DeviceType.IOT}>IoT / Other</option>
                  </select>
                </div>
              </div>
            </div>

            <div className="h-px bg-slate-700 w-full"></div>

            {/* SNMP Config */}
            <div>
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                <Shield className="w-4 h-4" /> SNMP Details
              </h3>
              
              <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-700 space-y-4">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div className="col-span-1 space-y-1">
                    <label className="text-xs font-medium text-slate-400">Version</label>
                    <select 
                      className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                      value={formData.snmpVersion}
                      onChange={e => setFormData({...formData, snmpVersion: e.target.value as SnmpVersion})}
                    >
                      <option value={SnmpVersion.V1}>v1</option>
                      <option value={SnmpVersion.V2C}>v2c</option>
                      <option value={SnmpVersion.V3}>v3</option>
                    </select>
                  </div>
                  <div className="col-span-1 space-y-1">
                    <label className="text-xs font-medium text-slate-400">Port</label>
                    <input 
                      type="number" 
                      className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                      value={formData.snmpPort}
                      onChange={e => setFormData({...formData, snmpPort: parseInt(e.target.value)})}
                    />
                  </div>
                  
                  {formData.snmpVersion !== SnmpVersion.V3 ? (
                    <div className="col-span-2 space-y-1">
                       <label className="text-xs font-medium text-slate-400">Community String</label>
                       <input 
                         type="text" 
                         className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm font-mono"
                         value={formData.snmpCommunity}
                         onChange={e => setFormData({...formData, snmpCommunity: e.target.value})}
                       />
                    </div>
                  ) : (
                    <>
                      <div className="col-span-2 space-y-1">
                         <label className="text-xs font-medium text-slate-400">Username</label>
                         <input 
                           type="text"
                           className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                           value={formData.snmpUser}
                           onChange={e => setFormData({...formData, snmpUser: e.target.value})}
                         />
                      </div>
                      <div className="col-span-2 space-y-1">
                         <label className="text-xs font-medium text-slate-400">Auth Protocol</label>
                         <select 
                           className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                           value={formData.snmpAuth}
                           onChange={e => setFormData({...formData, snmpAuth: e.target.value})}
                         >
                           <option value="SHA">SHA</option>
                           <option value="MD5">MD5</option>
                         </select>
                      </div>
                      <div className="col-span-2 space-y-1">
                         <label className="text-xs font-medium text-slate-400">Priv Protocol</label>
                         <select 
                           className="w-full bg-slate-800 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
                           value={formData.snmpPriv}
                           onChange={e => setFormData({...formData, snmpPriv: e.target.value})}
                         >
                           <option value="AES">AES</option>
                           <option value="DES">DES</option>
                         </select>
                      </div>
                    </>
                  )}
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col md:flex-row gap-3 items-center pt-2">
               <button
                 type="button"
                 onClick={handleTestConnection}
                 disabled={loading}
                 className="flex-1 w-full px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-medium text-sm transition-colors flex items-center justify-center gap-2"
               >
                 {loading ? <RotateCw className="w-4 h-4 animate-spin"/> : <Radio className="w-4 h-4" />}
                 Test Connection
               </button>

               <button
                 type="submit"
                 disabled={loading || !formData.name || !formData.ip}
                 className={`flex-1 w-full px-4 py-2 rounded-lg font-bold text-white shadow-lg flex items-center justify-center gap-2 transition-all text-sm ${
                   testStatus === 'success' 
                    ? 'bg-blue-600 hover:bg-blue-500 hover:scale-105'
                    : 'bg-blue-600/50 hover:bg-blue-600'
                 }`}
               >
                 <Save className="w-4 h-4" />
                 Save Device
               </button>
            </div>
            
            {statusMessage && (
              <div className={`p-3 rounded-lg text-sm border ${
                testStatus === 'success' || submitStatus === 'success' 
                  ? 'bg-green-900/20 border-green-500/50 text-green-300' :
                testStatus === 'error' || submitStatus === 'error' 
                  ? 'bg-red-900/20 border-red-500/50 text-red-300' :
                'bg-slate-900 border-slate-700 text-slate-400'
              }`}>
                {statusMessage}
              </div>
            )}
          </form>
        </div>

        {/* Right Column */}
        <div className="lg:col-span-1 space-y-6">
          
          {/* Card: Bulk Import */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-xl">
             <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-emerald-600/20 rounded-lg">
                  <FileSpreadsheet className="w-5 h-5 text-emerald-400" />
                </div>
                <h3 className="font-bold text-white">Bulk Operations</h3>
             </div>
             
             <div className="space-y-4">
                <div className="p-4 bg-slate-900 rounded-lg border border-dashed border-slate-600 text-center">
                   <p className="text-xs text-slate-400 mb-3">
                     Import devices via Excel (CSV)
                   </p>
                   
                   <input 
                     type="file" 
                     accept=".csv"
                     ref={fileInputRef}
                     onChange={handleFileUpload}
                     className="hidden"
                   />
                   
                   <div className="flex gap-2 justify-center">
                     <button 
                        onClick={() => fileInputRef.current?.click()}
                        className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs font-medium text-white flex items-center gap-2"
                     >
                       <UploadCloud className="w-3 h-3" /> Select File
                     </button>
                     <button 
                        onClick={handleDownloadTemplate}
                        className="px-3 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-xs font-medium text-slate-300 flex items-center gap-2"
                     >
                       <FileDown className="w-3 h-3" /> Template
                     </button>
                   </div>
                   <p className="text-[10px] text-slate-500 mt-2">Format: name,ip,type,location...</p>
                </div>

                {importError && (
                  <div className="bg-red-900/20 border border-red-900/50 rounded-lg p-3">
                     <p className="text-red-300 text-xs mb-2">{importError}</p>
                     <button 
                       onClick={handleAnalyzeError}
                       className="w-full py-1.5 bg-red-600/80 hover:bg-red-600 text-white rounded text-xs flex items-center justify-center gap-2 transition-colors"
                     >
                        <Brain className="w-3 h-3" /> Analyze with AI
                     </button>
                  </div>
                )}

                {importedDevices.length > 0 && !importError && (
                  <div className="animate-fade-in">
                    <div className="flex justify-between items-center mb-2">
                       <span className="text-xs text-emerald-400 font-bold">{importedDevices.length} devices found</span>
                       <button onClick={() => setImportedDevices([])} className="text-[10px] text-slate-500 hover:text-red-400">Clear</button>
                    </div>
                    <div className="max-h-60 overflow-y-auto bg-slate-900 rounded-lg border border-slate-700 divide-y divide-slate-800 mb-3 custom-scrollbar">
                       {importedDevices.map((d, idx) => (
                         <div key={d.id} className="p-2 flex justify-between items-center group">
                            <div className="overflow-hidden">
                               <p className="text-xs text-white truncate font-medium">{d.name}</p>
                               <p className="text-[10px] text-slate-500 font-mono">{d.ip} | {d.type}</p>
                            </div>
                            <button onClick={() => removeImportItem(d.id)} className="text-slate-600 hover:text-red-500">
                               <XCircle className="w-3 h-3" />
                            </button>
                         </div>
                       ))}
                    </div>
                    <button 
                      onClick={confirmImport}
                      className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold flex items-center justify-center gap-2"
                    >
                      <FileUp className="w-3 h-3" /> Import All
                    </button>
                  </div>
                )}
             </div>
          </div>

          {/* Card: System Security */}
          <div className="bg-slate-800 rounded-xl p-6 border border-slate-700 shadow-xl">
             <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-rose-600/20 rounded-lg">
                  <LockKeyhole className="w-5 h-5 text-rose-400" />
                </div>
                <div>
                  <h3 className="font-bold text-white">System Security</h3>
                  <p className="text-[10px] text-slate-400">Protect Kiosk Mode</p>
                </div>
             </div>

             <form onSubmit={handleUpdatePin} className="space-y-3">
                <div>
                   <label className="text-xs text-slate-400 mb-1 block">Change Access PIN</label>
                   <div className="flex gap-2">
                      <div className="relative flex-1">
                        <Key className="absolute left-2 top-2 w-4 h-4 text-slate-500" />
                        <input 
                           type="text" 
                           placeholder="New PIN (e.g. 1234)"
                           className="w-full bg-slate-900 border border-slate-600 rounded px-2 py-1.5 pl-8 text-white text-sm focus:ring-1 focus:ring-rose-500 outline-none"
                           value={newPin}
                           onChange={e => setNewPin(e.target.value.replace(/\D/g, '').slice(0, 8))}
                        />
                      </div>
                      <button 
                        type="submit"
                        disabled={!newPin}
                        className="px-3 py-1.5 bg-rose-600 hover:bg-rose-500 disabled:bg-slate-700 disabled:text-slate-500 text-white rounded text-xs font-bold transition-colors"
                      >
                        Update
                      </button>
                   </div>
                   <p className="text-[10px] text-slate-500 mt-1">Default PIN is 0000.</p>
                   {pinMessage && <p className="text-xs text-emerald-400 mt-1 animate-fade-in">{pinMessage}</p>}
                </div>
             </form>
          </div>

          {/* Tips Card */}
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
             <h4 className="text-xs font-bold text-slate-300 mb-2 uppercase">Quick Tips</h4>
             <ul className="text-xs text-slate-400 space-y-2 list-disc pl-4">
                <li>Use <span className="text-slate-200">public</span> as community string for testing.</li>
                <li>Ensure Firewall allows UDP port 161.</li>
                <li>For Excel, use <span className="text-slate-200">Save As CSV (Comma delimited)</span>.</li>
             </ul>
          </div>

        </div>

      </div>
    </div>
  );
};

export default AdminPanel;