import React, { useState } from 'react';
import { Device, DeviceType, DeviceStatus, SnmpVersion, AVAILABLE_LOCATIONS } from '../types';
import { Server, Monitor, Wifi, Plus, Trash2, Search, Cpu, HardDrive } from './Icons';

interface DeviceManagerProps {
  devices: Device[];
  onAddDevice: (device: Device) => void;
  onRemoveDevice: (id: string) => void;
}

const DeviceManager: React.FC<DeviceManagerProps> = ({ devices, onAddDevice, onRemoveDevice }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<DeviceType | 'ALL'>('ALL');

  // Form State
  const [newDevice, setNewDevice] = useState<Partial<Device> & { snmpCommunity?: string }>({
    name: '',
    ip: '',
    type: DeviceType.SERVER,
    location: AVAILABLE_LOCATIONS[0],
    snmpCommunity: 'public'
  });

  const handleAdd = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDevice.name || !newDevice.ip) return;

    // Device data will be set by backend API with default values
    const device: Device = {
      id: '', // Will be generated by backend
      name: newDevice.name,
      ip: newDevice.ip,
      type: newDevice.type as DeviceType,
      status: DeviceStatus.OFFLINE, // Default to OFFLINE until monitored
      cpuUsage: 0, // Default values - backend will update when device is monitored
      memoryUsage: 0,
      temperature: null,
      uptime: 0,
      lastSeen: new Date().toISOString(),
      location: newDevice.location || AVAILABLE_LOCATIONS[0],
      snmpConfig: {
        version: SnmpVersion.V2C,
        port: 161,
        community: newDevice.snmpCommunity,
        timeout: 2000
      }
    };

    onAddDevice(device);
    setIsModalOpen(false);
    setNewDevice({ name: '', ip: '', type: DeviceType.SERVER, location: AVAILABLE_LOCATIONS[0], snmpCommunity: 'public' });
  };

  const filteredDevices = devices.filter(d => {
    const matchesSearch = d.name.toLowerCase().includes(searchTerm.toLowerCase()) || d.ip.includes(searchTerm);
    const matchesType = filterType === 'ALL' || d.type === filterType;
    return matchesSearch && matchesType;
  });

  const getIcon = (type: DeviceType) => {
    switch (type) {
      case DeviceType.SERVER: return <Server className="w-5 h-5" />;
      case DeviceType.NETWORK: return <Wifi className="w-5 h-5" />;
      case DeviceType.PC: return <Monitor className="w-5 h-5" />;
      default: return <Server className="w-5 h-5" />;
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-slate-800 p-4 rounded-xl border border-slate-700 shadow-sm">
        <div className="relative flex-1 w-full md:w-auto">
          <Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search devices by Name or IP..."
            className="w-full bg-slate-900 border border-slate-700 text-slate-200 pl-10 pr-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <div className="flex gap-2 w-full md:w-auto overflow-x-auto">
          {['ALL', DeviceType.SERVER, DeviceType.NETWORK, DeviceType.PC].map(type => (
            <button
              key={type}
              onClick={() => setFilterType(type as any)}
              className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${
                filterType === type 
                  ? 'bg-blue-600 text-white' 
                  : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
              }`}
            >
              {type}
            </button>
          ))}
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-sm font-medium transition-colors ml-auto md:ml-2 whitespace-nowrap"
          >
            <Plus className="w-4 h-4" /> Add Device
          </button>
        </div>
      </div>

      {filteredDevices.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <Server className="w-16 h-16 text-slate-600 mb-4" />
          <h3 className="text-lg font-bold text-slate-400 mb-2">
            {searchTerm || filterType !== 'ALL' ? 'No devices found' : 'No devices yet'}
          </h3>
          <p className="text-sm text-slate-500 mb-4">
            {searchTerm || filterType !== 'ALL' 
              ? 'Try adjusting your search or filter criteria'
              : 'Get started by adding your first device to monitor'}
          </p>
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-sm font-medium transition-colors"
          >
            <Plus className="w-4 h-4" /> Add Device
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 overflow-y-auto pb-4 custom-scrollbar">
          {filteredDevices.map(device => (
          <div key={device.id} className={`relative bg-slate-800 rounded-xl border ${
            device.status === DeviceStatus.OFFLINE ? 'border-red-900/50' :
            device.status === DeviceStatus.CRITICAL ? 'border-red-900/50' :
            device.status === DeviceStatus.WARNING ? 'border-yellow-900/50' :
            'border-slate-700'
          } p-5 shadow-lg hover:shadow-xl transition-all group`}>
             <button 
                onClick={() => onRemoveDevice(device.id)}
                className="absolute top-4 right-4 p-2 text-slate-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"
                title="Remove Device"
             >
               <Trash2 className="w-4 h-4" />
             </button>

             <div className="flex items-start justify-between mb-4">
               <div className="flex items-center gap-3">
                 <div className={`p-3 rounded-lg ${
                   device.type === DeviceType.SERVER ? 'bg-indigo-500/20 text-indigo-400' :
                   device.type === DeviceType.NETWORK ? 'bg-orange-500/20 text-orange-400' :
                   'bg-cyan-500/20 text-cyan-400'
                 }`}>
                   {getIcon(device.type)}
                 </div>
                 <div>
                   <h3 className="font-bold text-white text-lg">{device.name}</h3>
                   <div className="flex items-center gap-2 text-xs text-slate-400 font-mono">
                     {device.ip} 
                     {device.status === DeviceStatus.ONLINE && (
                       <span className="text-green-500 flex items-center gap-1">
                         ● Online
                       </span>
                     )}
                     {device.status === DeviceStatus.OFFLINE && (
                       <span className="text-red-500 flex items-center gap-1">
                         ● Offline
                       </span>
                     )}
                     {device.status === DeviceStatus.WARNING && (
                       <span className="text-yellow-500 flex items-center gap-1">
                         ● Warning
                       </span>
                     )}
                     {device.status === DeviceStatus.CRITICAL && (
                       <span className="text-red-500 flex items-center gap-1">
                         ● Critical
                       </span>
                     )}
                   </div>
                 </div>
               </div>
             </div>

             <div className="grid grid-cols-2 gap-4 mt-4">
                <div className="bg-slate-900/50 p-3 rounded-lg">
                  <div className="flex items-center gap-2 text-slate-400 text-xs mb-1">
                    <Cpu className="w-3 h-3" /> CPU Load
                  </div>
                  <div className="flex items-end gap-2">
                    <span className={`text-xl font-bold ${device.cpuUsage > 80 ? 'text-red-400' : 'text-slate-200'}`}>
                      {device.cpuUsage}%
                    </span>
                    <div className="flex-1 h-1.5 bg-slate-700 rounded-full mb-1.5">
                      <div 
                        className={`h-full rounded-full ${device.cpuUsage > 80 ? 'bg-red-500' : 'bg-blue-500'}`} 
                        style={{ width: `${device.cpuUsage}%` }}
                      ></div>
                    </div>
                  </div>
                </div>

                <div className="bg-slate-900/50 p-3 rounded-lg">
                  <div className="flex items-center gap-2 text-slate-400 text-xs mb-1">
                    <HardDrive className="w-3 h-3" /> Memory
                  </div>
                  <div className="flex items-end gap-2">
                    <span className={`text-xl font-bold ${device.memoryUsage > 90 ? 'text-yellow-400' : 'text-slate-200'}`}>
                      {device.memoryUsage}%
                    </span>
                    <div className="flex-1 h-1.5 bg-slate-700 rounded-full mb-1.5">
                      <div 
                        className={`h-full rounded-full ${device.memoryUsage > 90 ? 'bg-yellow-500' : 'bg-purple-500'}`} 
                        style={{ width: `${device.memoryUsage}%` }}
                      ></div>
                    </div>
                  </div>
                </div>
             </div>

             <div className="mt-4 pt-4 border-t border-slate-700/50 flex justify-between text-xs text-slate-500">
                <span>Loc: {device.location || 'N/A'}</span>
                <span>Temp: {device.temperature !== null && device.temperature !== undefined ? `${device.temperature}°C` : 'N/A'}</span>
             </div>
          </div>
        ))}
        </div>
      )}

      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-slate-800 rounded-2xl shadow-2xl w-full max-w-md border border-slate-700">
            <div className="p-6 border-b border-slate-700">
              <h2 className="text-xl font-bold text-white">Add New Device</h2>
              <p className="text-sm text-slate-400">Configure SNMP or IP monitoring agent</p>
            </div>
            <form onSubmit={handleAdd} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Device Name</label>
                <input
                  required
                  type="text"
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                  value={newDevice.name}
                  onChange={e => setNewDevice({...newDevice, name: e.target.value})}
                  placeholder="e.g., Web-Server-01"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1">IP Address</label>
                  <input
                    required
                    type="text"
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                    value={newDevice.ip}
                    onChange={e => setNewDevice({...newDevice, ip: e.target.value})}
                    placeholder="192.168.1.10"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1">Type</label>
                  <select
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                    value={newDevice.type}
                    onChange={e => setNewDevice({...newDevice, type: e.target.value as DeviceType})}
                  >
                    {Object.values(DeviceType).map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Location</label>
                <select
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                  value={newDevice.location}
                  onChange={e => setNewDevice({...newDevice, location: e.target.value})}
                >
                  {AVAILABLE_LOCATIONS.map(loc => (
                    <option key={loc} value={loc}>{loc}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">SNMP Community (Optional)</label>
                <input
                  type="password"
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg p-2 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                  value={newDevice.snmpCommunity}
                  onChange={e => setNewDevice({...newDevice, snmpCommunity: e.target.value})}
                  placeholder="public"
                />
              </div>
              <div className="flex justify-end gap-3 mt-6">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg text-sm font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium"
                >
                  Add Device
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default DeviceManager;